import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import '@stream-io/video-react-sdk/dist/css/styles.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job We Met",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider 
      appearance={{
        layout: {
          logoImageUrl:"/jwmeet.png",
          socialButtonsVariant:"iconButton"
        },
        variables: {
          colorText: "#000000",
          colorBackground: "#ffffff",
          colorPrimary: "#0096FF"
        }
      }}
      >
      <body className={inter.className}>
        {children}
      </body>
      </ClerkProvider>

    </html>
  );
}
